import { User, HelpRequest, Message, Notification, LeaderboardEntry } from "./types"

export const mockUsers: User[] = [
  {
    id: "1",
    name: "Ayesha Khan",
    email: "ayesha@helphub.ai",
    role: "both",
    location: "Karachi",
    skills: ["Figma", "UI/UX", "HTML/CSS", "Career Guidance"],
    interests: ["Hackathons", "UI/UX", "Community Building"],
    trustScore: 100,
    contributions: 35,
    badges: ["Design Ally", "Fast Responder", "Top Mentor"],
  },
  {
    id: "2",
    name: "Hassan Ali",
    email: "hassan@helphub.ai",
    role: "can-help",
    location: "Lahore",
    skills: ["JavaScript", "React", "Git/GitHub"],
    interests: ["Open Source", "Web Development"],
    trustScore: 88,
    contributions: 24,
    badges: ["Code Rescuer", "Bug Hunter"],
  },
  {
    id: "3",
    name: "Sara Noor",
    email: "sara@helphub.ai",
    role: "both",
    location: "Karachi",
    skills: ["Python", "Data Analysis"],
    interests: ["Data Science", "Machine Learning"],
    trustScore: 74,
    contributions: 11,
    badges: ["Community Voice"],
  },
]

export const mockRequests: HelpRequest[] = [
  {
    id: "1",
    title: "Need help",
    description: "helpn needed",
    category: "Web Development",
    urgency: "high",
    status: "solved",
    tags: ["JavaScript", "Debugging", "Review"],
    authorId: "1",
    authorName: "Ayesha Khan",
    authorLocation: "Karachi",
    helpersInterested: 1,
    createdAt: new Date(),
  },
  {
    id: "2",
    title: "Need help making my portfolio responsive before demo day",
    description: "My HTML/CSS portfolio breaks on tablets and I need layout guidance before tomorrow evening.",
    category: "Web Development",
    urgency: "high",
    status: "solved",
    tags: ["HTML/CSS", "Responsive", "Portfolio"],
    authorId: "3",
    authorName: "Sara Noor",
    authorLocation: "Karachi",
    helpersInterested: 1,
    createdAt: new Date(),
  },
  {
    id: "3",
    title: "Looking for Figma feedback on a volunteer event poster",
    description: "I have a draft poster for a campus community event and want sharper hierarchy, spacing, and CTA copy.",
    category: "Design",
    urgency: "medium",
    status: "open",
    tags: ["Figma", "Poster", "Design Review"],
    authorId: "1",
    authorName: "Ayesha Khan",
    authorLocation: "Lahore",
    helpersInterested: 1,
    createdAt: new Date(),
  },
  {
    id: "4",
    title: "Need mock interview support for internship applications",
    description: "Applying to frontend internships and need someone to practice behavioral and technical interview questions with me.",
    category: "Career",
    urgency: "low",
    status: "solved",
    tags: ["Interview Prep", "Career", "Frontend"],
    authorId: "3",
    authorName: "Sara Noor",
    authorLocation: "Remote",
    helpersInterested: 2,
    createdAt: new Date(),
  },
]

export const mockMessages: Message[] = [
  {
    id: "1",
    fromUserId: "1",
    fromUserName: "Ayesha Khan",
    toUserId: "3",
    toUserName: "Sara Noor",
    content: "I checked your portfolio request. Share the breakpoint screenshots and I can suggest fixes.",
    timestamp: new Date(Date.now() - 3600000),
    read: false,
  },
  {
    id: "2",
    fromUserId: "2",
    fromUserName: "Hassan Ali",
    toUserId: "1",
    toUserName: "Ayesha Khan",
    content: "Your event poster concept is solid. I would tighten the CTA and reduce the background texture.",
    timestamp: new Date(Date.now() - 7200000),
    read: false,
  },
]

export const mockNotifications: Notification[] = [
  {
    id: "1",
    userId: "1",
    type: "status",
    title: '"Need help" was marked as solved',
    description: "Status",
    timestamp: new Date(),
    read: false,
  },
  {
    id: "2",
    userId: "1",
    type: "match",
    title: 'Ayesha Khan offered help on "Need help"',
    description: "Match",
    timestamp: new Date(),
    read: false,
  },
  {
    id: "3",
    userId: "1",
    type: "request",
    title: 'Your request "Need help" is now live in the community feed',
    description: "Request",
    timestamp: new Date(),
    read: false,
  },
  {
    id: "4",
    userId: "1",
    type: "status",
    title: '"Need help making my portfolio responsive before demo day" was marked as solved',
    description: "Status",
    timestamp: new Date(),
    read: false,
  },
  {
    id: "5",
    userId: "1",
    type: "match",
    title: "New helper matched to your responsive portfolio request",
    description: "Match",
    timestamp: new Date(Date.now() - 720000),
    read: false,
  },
  {
    id: "6",
    userId: "1",
    type: "reputation",
    title: "Your trust score increased after a solved request",
    description: "Reputation",
    timestamp: new Date(Date.now() - 3600000),
    read: false,
  },
  {
    id: "7",
    userId: "1",
    type: "insight",
    title: "AI Center detected rising demand for interview prep",
    description: "Insight",
    timestamp: new Date(Date.now() - 86400000),
    read: true,
  },
]

export const mockLeaderboard: LeaderboardEntry[] = [
  {
    userId: "1",
    name: "Ayesha Khan",
    skills: ["Figma", "UI/UX", "HTML/CSS"],
    trustScore: 100,
    contributions: 35,
    badges: ["Design Ally", "Fast Responder", "Top Mentor"],
    rank: 1,
  },
  {
    userId: "2",
    name: "Hassan Ali",
    skills: ["JavaScript", "React", "Git/GitHub"],
    trustScore: 88,
    contributions: 24,
    badges: ["Code Rescuer", "Bug Hunter"],
    rank: 2,
  },
  {
    userId: "3",
    name: "Sara Noor",
    skills: ["Python", "Data Analysis"],
    trustScore: 74,
    contributions: 11,
    badges: ["Community Voice"],
    rank: 3,
  },
]
